export const userConstants = {
  ACCOUNT_DELETE_WATCHER: 'ACCOUNT_DELETE_WATCHER',
  ACCOUNT_UPDATE_WATCHER: 'ACCOUNT_UPDATE_WATCHER',

  GET_FILELISTS_WATCHER: 'GET_FILELISTS_WATCHER',

  FILE_UPLOAD_WATCHER: 'FILE_UPLOAD_WATCHER',
  FILE_DOWNLOAD_WATCHER: 'FILE_DOWNLOAD_WATCHER',
  FILE_UPLOAD_SUCCESS: 'FILE_UPLOAD_SUCCESS',

  LOGIN_WATCHER: 'LOGIN_WATCHER',

  SAVE_FILE_INFO: 'SAVE_FILE_INFO',
  SAVE_USER_INFO: 'SAVE_USER_INFO',
  SIGNUP_WATCHER: 'SIGNUP_WATCHER',

  USER_MANAGE_WATCHER: 'USER_MANAGE_WATCHER',
  USER_LOGIN: 'USER_LOGIN',
  USER_SIGNUP: 'USER_SIGNUP',
  USER_LOGOUT: 'USER_LOGOUT'
};
