export const userConstants = {
  USER_LOGIN: 'USER_LOGIN',
  USER_SIGNUP: 'USER_SIGNUP',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_INFO: 'USER_INFO',

  LOGIN_WATCHER: 'LOGIN_WATCHER',
  SIGNUP_WATCHER: 'SIGNUP_WATCHER',
  ACCOUNT_DELETE_WATCHER: 'ACCOUNT_DELETE_WATCHER',
  ACCOUNT_UPDATE_WATCHER: 'ACCOUNT_UPDATE_WATCHER',
  USER_MANAGE_WATCHER: 'USER_MANAGE_WATCHER',

  FILE_UPLOAD_WATCHER: 'FILE_UPLOAD_WATCHER',
  FILE_DOWNLOAD_WATCHER: 'FILE_DOWNLOAD_WATCHER',
  FILE_DOWNLOAD_START_WATCHER: 'FILE_DOWNLOAD_START_WATCHER'
};
