export const userConstants = {
  USER_LOGIN: 'USER_LOGIN',
  USER_SIGNUP: 'USER_SIGNUP',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_INFO: 'USER_INFO',

  LOGIN_WATCHER: 'LOGIN_WATCHER',
  SIGNUP_WATCHER: 'SIGNUP_WATCHER',
  ACCOUNTDELETE_WATCHER: 'ACCOUNTDELETE_WATCHER',
  ACCOUNTUPDATE_WATCHER: 'ACCOUNTUPDATE_WATCHER',
  USERMANAGE_WATCHER: 'USERMANAGE_WATCHER'
};
